version: '3.8'

services:

    app:
        build:
            context: .
            dockerfile: /docker/app/Dockerfile
        volumes:
            - ./:/var/www/laravel.test.api
        extra_hosts:
            - host.docker.internal:host-gateway
        depends_on:
            - mysql
        container_name: app

    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/laravel.test.api
            - ./docker/nginx:/etc/nginx/conf.d
        ports:
            - 8098:80
        depends_on:
            - app
        container_name: nginx

    mysql:
        image: mysql:8
        restart: always
        volumes:
            - ./docker/db-data:/var/lib/mysql
        ports:
            - 33061:3306
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_ROOT_PASSWORD: root
        container_name: mysql

    node:
        image: node:lts
        volumes:
            - ./:/var/www/laravel.test.api
            - ./node_modules:/usr/src/node_modules
        working_dir: /var/www/laravel.test.api
        tty: true
        container_name: npm
